import { MenuItem } from './types';
export const API_BASE = "http://localhost:8080/api/emberash";


// Updated with verified high-quality Unsplash Images
export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Smoked Truffle Crostini',
    description: 'Charred artisan bread, wild mushroom pate, truffle oil, and microgreens.',
    price: 14,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=800&q=80',
    calories: 320,
    isVegetarian: true,
  },
  {
    id: '6',
    name: 'Crispy Calamari',
    description: 'Tender squid rings, lightly battered, served with lemon aioli and parsley.',
    price: 16,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?auto=format&fit=crop&w=800&q=80',
    calories: 450,
  },
  {
    id: '10',
    name: 'Artisan Cheese Board',
    description: 'Selection of aged cheeses, honeycomb, nuts, and house-made crackers.',
    price: 24,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    calories: 800,
    isVegetarian: true,
  },
  {
    id: '12',
    name: 'Wagyu Beef Carpaccio',
    description: 'Thinly sliced raw wagyu beef, parmesan shavings, truffle oil, and arugula.',
    price: 22,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    calories: 280,
  },
  {
    id: '2',
    name: 'Wagyu Smash Burger',
    description: 'Double wagyu patty, aged cheddar, smoky bacon jam, and garlic aioli on brioche.',
    price: 26,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80',
    calories: 950,
  },
  {
    id: '3',
    name: 'Pan-Seared Scallops',
    description: 'Jumbo scallops, cauliflower purée, crispy pancetta, and herb oil.',
    price: 32,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&w=800&q=80',
    calories: 420,
  },
  {
    id: '4',
    name: 'Fire-Roasted Pasta',
    description: 'Fresh pappardelle with roasted red pepper sauce, burrata, and chili flakes.',
    price: 22,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=800&q=80',
    calories: 780,
    isVegetarian: true,
    isSpicy: true,
  },
  {
    id: '5',
    name: 'Herb-Crusted Lamb Rack',
    description: 'Served pink with fondant potatoes, seasonal greens, and a red wine reduction.',
    price: 38,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=800&q=80',
    calories: 850,
  },
  {
    id: '9',
    name: 'Charcoal Grilled Salmon',
    description: 'Wild-caught salmon fillet, asparagus spears, and lemon butter sauce.',
    price: 29,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&w=800&q=80',
    calories: 620,
  },
  {
    id: '13',
    name: 'Smoked BBQ Pork Ribs',
    description: 'Slow-cooked ribs glazed in a house-made smoky barbecue sauce, served with coleslaw.',
    price: 34,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    calories: 1100,
  },
  {
    id: '7',
    name: 'Molten Dark Chocolate Cake',
    description: 'Rich warm chocolate center, vanilla bean gelato, and raspberry coulis.',
    price: 12,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    calories: 560,
    isVegetarian: true,
  },
  {
    id: '14',
    name: 'Burnt Basque Cheesecake',
    description: 'Creamy, caramelized cheesecake with a rustic burnt top and berry compote.',
    price: 14,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    calories: 480,
    isVegetarian: true,
  },
   {
    id: '16',
    name: 'Classic Tiramisu',
    description: 'Layers of coffee-soaked ladyfingers and mascarpone cream, dusted with cocoa.',
    price: 13,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    calories: 420,
    isVegetarian: true,
  },
  {
    id: '8',
    name: 'Smoked Old Fashioned',
    description: 'Bourbon, maple syrup, angostura bitters, smoked with cherry wood.',
    price: 15,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&w=800&q=80',
    calories: 180,
    isVegetarian: true,
  },
  {
    id: '11',
    name: 'Espresso Martini',
    description: 'Vodka, fresh espresso, coffee liqueur, and three coffee beans.',
    price: 16,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    calories: 210,
    isVegetarian: true,
  },
  {
    id: '15',
    name: 'Spicy Mezcal Margarita',
    description: 'Mezcal, fresh lime juice, agave syrup, and jalapeño slices with a chili salt rim.',
    price: 17,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    calories: 190,
    isVegetarian: true,
    isSpicy: true,
  }
];

export const SYSTEM_INSTRUCTION = `You are Sebastian, a sophisticated and charming AI concierge for "Ember & Ash", a high-end restaurant.
Your tone is warm, professional, and slightly poetic. You are knowledgeable about food, wine pairings, and dietary requirements.
If asked about the menu, recommend items from the provided list based on user preferences.
If asked about bookings, guide them to the booking form below.
Current menu items: ${MENU_ITEMS.map(i => i.name).join(', ')}.
Do not mention prices unless asked. Keep responses concise (under 50 words) unless detailed explanation is requested.`;